### ISSUE TITLE
Regarding execution

### ISSUE THREAD

**Issue by dhirensoneji** [raff-k/RainSlide#1]
Hello, can you please tell how to run this project?

**Comment by raff-k** [comment]
Have you tried: `devtools::install_github("raff-k/RainSlide")`?

**Comment by dhirensoneji** [comment]
Where do I exactly type this?

**Comment by raff-k** [comment]
The package is [R](https://en.wikipedia.org/wiki/R_(programming_language)) based. Thus, you need the appropriate environment and some programming skill.

Well, feel free to re-open the issue if you have more function-related questions
